version: '3'

volumes:
  postgres_data: {}

services:
  backend:
    build:
      dockerfile: ./infra/Dockerfile
      context: .
    ports:
      - "8700:8700"
    volumes:
      - ./backend:/app
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: 'postgres'
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
