# Generated by Django 5.0.3 on 2024-03-24 23:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("018e72d5-2e9d-7236-bfe3-d09d0c2a44ef"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("uid", models.BinaryField(max_length=6)),
                ("last_swiped", models.DateTimeField()),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PhorgeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("over_18", models.BooleanField()),
                ("member_until", models.DateField()),
                ("member_since", models.DateField()),
                ("last_access", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Restriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_from", models.DateField()),
                ("time_to", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="CardSwipeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="access_control.card",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="access_control.phorgemember",
            ),
        ),
    ]
