# Generated by Django 5.0.3 on 2024-03-24 23:48

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cardswipelog",
            old_name="card_id",
            new_name="card",
        ),
        migrations.AddField(
            model_name="cardswipelog",
            name="swiped_on",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 24, 23, 48, 41, 45459)
            ),
        ),
        migrations.AddField(
            model_name="cardswipelog",
            name="unlock",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("018e72dd-c7d5-7f57-a5a4-210a551e117f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
