# Generated by Django 5.0.3 on 2024-04-22 01:20

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0003_alter_card_id_alter_card_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phorgemember",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("018f0364-22db-7e40-9501-45a99c8d3425"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="cardswipelog",
            name="swiped_on",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 22, 1, 20, 45, 276266)
            ),
        ),
    ]
