# Generated by Django 5.0.3 on 2024-04-22 01:22

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0004_phorgemember_birth_date_alter_card_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("018f0365-4d12-74fb-9b0b-c289c573ea89"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="cardswipelog",
            name="swiped_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 22, 1, 22, 1, 619250, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
