# Generated by Django 5.0.3 on 2024-04-22 01:22

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0005_alter_card_id_alter_cardswipelog_swiped_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("018f0365-e1e7-7272-8618-8075b6d2d863"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="cardswipelog",
            name="swiped_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 22, 1, 22, 39, 719442, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
