# Generated by Django 5.0.3 on 2024-04-22 01:25

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0006_alter_card_id_alter_cardswipelog_swiped_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("018f0368-9a35-7963-82ea-7f448ebe3098"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="last_swiped",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cardswipelog",
            name="swiped_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 22, 1, 25, 37, 973513, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="phorgemember",
            name="last_access",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
